#!/usr/bin/env python3
"""Bake per-state province data into script.

Two things the engine cannot do at runtime, so they are generated here from map_data:

1. Enumerating the provinces of a state. There is no state-scoped province iterator,
   but declaring a geographic region over a state region makes the game generate
   `every_province_in_<short_key>`, so this file only has to declare those regions.
2. Transferring a province held in a scope. `set_owner_of_provinces` only accepts
   literal ids; PostValidate rejects `provinces = { scope:x }`.

Run: python tools/bake_provinces.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify_map_data import find_game, parse_state_regions, parse_terrains  # noqa: E402

HUB_ORDER = ('city', 'port', 'farm', 'mine', 'wood')

MOD = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = ('# Generated by tools/bake_provinces.py - do not edit by hand.\n'
          '# Source: map_data/state_regions/*.txt\n\n')
NL = '\n'


def write(rel, text):
    path = os.path.join(MOD, *rel.split('/'))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8-sig', newline='\n') as f:
        f.write(text)
    return path


def short_key(name):
    """STATE_WALLONIA -> mbga_wallonia. The mbga_ prefix keeps these out of the way of
    vanilla and other mods, which share one namespace of geographic region short keys."""
    return 'mbga_' + name[len('STATE_'):].lower() if name.startswith('STATE_')         else 'mbga_' + name.lower()


def bake_geographic_regions(regions):
    """One geographic region per state region.

    Declaring a geographic region makes the game generate
    <any|every|ordered|random>_province_in_<short_key> iterators for it, which is the
    only way to walk a state's provinces at runtime.
    """
    out = [HEADER]
    for name in sorted(regions):
        out.append('mbga_geo_' + name + ' = {' + NL)
        out.append('	short_key = "' + short_key(name) + '"' + NL + NL)
        out.append('	state_regions = { ' + name + ' }' + NL)
        out.append('}' + NL + NL)
    return ''.join(out)


def bake_list_dispatch(regions):
    """State scope in, scope:actor's $LIST$ comes out holding that state's provinces.

    No filtering happens here. Which of those provinces are actually wanted is decided by
    the caller, so the same enumeration serves both the candidate list and the list of
    the demander's own bordering provinces.
    """
    out = [HEADER,
           '# state scope in, scope:actor receives the provinces in its $LIST$ variable list' + NL,
           'mbga_fill_provinces_of_state = {' + NL]
    first = True
    for name in sorted(regions):
        kw = 'if' if first else 'else_if'
        first = False
        out.append('	' + kw + ' = {' + NL)
        out.append('		limit = { state_region = s:' + name + ' }' + NL)
        out.append('		every_province_in_' + short_key(name) + ' = {' + NL)
        out.append('			save_scope_as = mbga_current_province' + NL)
        out.append('			scope:actor = { add_to_variable_list = { name = $LIST$'
                   ' target = scope:mbga_current_province } }' + NL)
        out.append('		}' + NL)
        out.append('	}' + NL)
    out.append('}' + NL + NL)
    out.append('mbga_fill_selectable_provinces = {' + NL)
    out.append('	scope:actor = { clear_variable_list = mbga_selectable }' + NL)
    out.append('	mbga_fill_provinces_of_state = { LIST = mbga_selectable }' + NL)
    out.append('}' + NL)
    return ''.join(out)


def bake_hub_lookup(regions):
    """Per state region, record which province is which hub.

    A hub is a single province, not a group, and the same province can be two hubs at
    once. Which province that is exists only in map_data/state_regions, so it is the one
    thing here that cannot be answered at runtime: script can set a hub's name but has no
    trigger or scope link that reads one back.
    """
    out = [HEADER, '# hub order: 1 city, 2 port, 3 farm, 4 mine, 5 wood' + NL + NL]
    for name in sorted(regions):
        out.append('mbga_hubs_' + name + ' = {' + NL)
        for kind in HUB_ORDER:
            pid = regions[name]['hubs'].get(kind)
            if pid:
                out.append('	set_variable = { name = mbga_hub_' + kind
                           + ' value = p:' + pid + ' }' + NL)
        out.append('}' + NL + NL)
    return ''.join(out)


def bake_hub_dispatch(regions):
    """State scope in, the caller's mbga_hub_* variables come out."""
    out = [HEADER, 'mbga_load_hubs_of_state = {' + NL]
    for kind in HUB_ORDER:
        out.append('	remove_variable = mbga_hub_' + kind + NL)
    first = True
    for name in sorted(regions):
        if not regions[name]['hubs']:
            continue
        kw = 'if' if first else 'else_if'
        first = False
        out.append('	' + kw + ' = {' + NL)
        out.append('		limit = { var:mbga_active_state_region ?= s:' + name + ' }' + NL)
        out.append('		mbga_hubs_' + name + ' = yes' + NL)
        out.append('	}' + NL)
    out.append('}' + NL)
    return ''.join(out)


def bake_transfers(regions):
    """Per region: match the province scope against literal ids and transfer."""
    out = [HEADER]
    for name in sorted(regions):
        out.append('mbga_transfer_in_' + name + ' = {' + NL)
        first = True
        for pid in regions[name]['provinces']:
            kw = 'if' if first else 'else_if'
            first = False
            out.append('\t' + kw + ' = { limit = { this = p:' + pid + ' } s:' + name
                       + ' = { set_owner_of_provinces = { country = scope:mbga_taker'
                       + ' provinces = { ' + pid + ' } } } }' + NL)
        out.append('}' + NL + NL)
    return ''.join(out)


def bake_transfer_dispatch(regions):
    """Province scope in, scope:mbga_taker receives it."""
    out = [HEADER, '# province scope in, scope:mbga_taker = receiving country' + NL,
           'mbga_transfer_province_to_taker = {' + NL]
    first = True
    for name in sorted(regions):
        kw = 'if' if first else 'else_if'
        first = False
        out.append('\t' + kw + ' = {' + NL)
        out.append('\t\tlimit = { state.state_region = s:' + name + ' }' + NL)
        out.append('\t\tmbga_transfer_in_' + name + ' = yes' + NL)
        out.append('\t}' + NL)
    out.append('}' + NL)
    return ''.join(out)


def main():
    game = find_game()
    if not game:
        print('Victoria 3 not found. Set VIC3_GAME.')
        return 2
    regions = {n: r for n, r in parse_state_regions(game).items() if r['provinces']}
    terrains = parse_terrains(game)

    written = [
        write('common/geographic_regions/mbga_state_regions.txt',
              bake_geographic_regions(regions)),
        write('common/scripted_effects/mbga_baked_dispatch.txt', bake_list_dispatch(regions)),
        write('common/scripted_effects/mbga_baked_hubs.txt', bake_hub_lookup(regions)),
        write('common/scripted_effects/mbga_baked_hub_dispatch.txt', bake_hub_dispatch(regions)),
        write('common/scripted_effects/mbga_baked_transfers.txt', bake_transfers(regions)),
        write('common/scripted_effects/mbga_baked_transfer_dispatch.txt',
              bake_transfer_dispatch(regions)),
    ]

    hub_lines = [HEADER]
    hubs = 0
    for name in sorted(regions):
        for kind, pid in sorted(regions[name]['hubs'].items()):
            hub_lines.append('# ' + name + ' ' + kind + ' = ' + pid
                             + ' (' + terrains.get(pid, '?') + ')' + NL)
            hubs += 1
    written.append(write('tools/generated_hub_reference.txt', ''.join(hub_lines)))

    for p in written:
        print(f'{os.path.relpath(p, MOD):<58}{os.path.getsize(p) // 1024:>6} KB')
    total = sum(len(r['provinces']) for r in regions.values())
    print(f'\nstate regions: {len(regions)}   provinces: {total}   named hubs: {hubs}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
