#!/usr/bin/env python3
"""Which provinces touch which, taken from the map itself.

Nothing in script can answer this. There are no coordinates and no province neighbours, and
the only way to ask is to hand a province to a country of its own and ask whether that
country borders another, which costs two province transfers per question. That works on any
map, and it is what makes a large state slow.

So the answer is worked out here instead, from map_data/provinces.png, where two provinces
are neighbours when their colours meet along a pixel edge, and from map_data/adjacencies.csv,
which carries the straits and canals joining provinces that meet nowhere at all. Neighbours
outside the state are
kept as well: whether a province touches the demander then becomes a question about who owns
them, which costs nothing at all. Water is left out, since no country owns it and an edge to
it can answer nothing.

What comes out is a lookup table the mod uses when it proves to describe the map being
played, and ignores when it does not.

Run tools/make_compat.py rather than this file: it does the whole set at once, for the base
game's map or for a mod's.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3_map import MapSource, find_game  # noqa: E402

CHUNKS = 8
NL = '\n'
T = '\t'
HEADER = ('# Generated by tools/make_compat.py - do not edit by hand.' + NL
          + '# Source: map_data/provinces.png and map_data/adjacencies.csv' + NL + NL)


def collect(source):
    """-> (edges by state region, impassable provinces, count with no land neighbour)

    Reach runs one way through impassable ground. A province that cannot be marched through
    can be reached from ordinary land, and taking it must not open anything ordinary beyond
    it - otherwise a mountain range becomes a road to the valley behind it.

    So an edge is kept only where it can carry reach that ought to travel: from an ordinary
    province the impassable neighbours are dropped, and between two impassable provinces
    nothing is kept at all, since the mod takes every impassable province in a state at once
    and never needs to walk from one to the next.
    """
    regions = source.state_regions()
    water = source.water()
    blocked = source.impassable()
    of_state = {}
    for name, r in regions.items():
        for pid in r['provinces']:
            of_state[int(pid[1:], 16)] = name

    by_state = {}
    # The pixels, and then the pairs that touch across water. A strait or a canal joins two
    # provinces that meet nowhere on the map, and the game counts them as neighbours.
    for a, b in list(source.edges()) + source.straits():
        a, b = int(a), int(b)
        sa, sb = of_state.get(a), of_state.get(b)
        if sa is None or sb is None:      # a colour no state region claims
            continue
        if a in water or b in water:      # nobody owns water, so the edge answers nothing
            continue
        if a in blocked and b in blocked:  # taken together, so never walked between
            continue
        if b not in blocked:               # reach into impassable ground, and out of it
            by_state.setdefault(sa, set()).add((a, b))
        if a not in blocked:               # but never out of it into ordinary land
            by_state.setdefault(sb, set()).add((b, a))

    named = {a for e in by_state.values() for a, _ in e}
    islands = {}
    for name, r in regions.items():
        alone = sum(1 for pid in r['provinces']
                    if int(pid[1:], 16) not in water and int(pid[1:], 16) not in named
                    and int(pid[1:], 16) not in blocked)
        if alone:
            islands[name] = alone
    return by_state, blocked, islands


def bake(by_state, blocked, by_region, islands):
    """-> {relative path: file text}. One effect per state region, and a dispatcher.

    A province's neighbours are dropped straight into the container wrapping it, found through
    the mbga_container_of map the mod fills as it builds them, so filling a state costs one
    lookup per province and no searching.

    A state region is one thing and a state is one owner's share of it, so a region split
    between owners holds provinces with no container. Each province is asked for before it is
    written to, since writing into a scope that is not there is an error the log would
    otherwise carry once per edge.

    A state also reports how many of its provinces have no land neighbour to name. Without
    that number an island would look like a province the table failed to answer for.
    """
    # A region made only of islands has nothing to file but is still answered for: its
    # island count alone tells the mod the table knows it and there is nothing to find.
    names = sorted(set(by_state) | set(islands) | set(by_region))
    files = {}
    for c in range(CHUNKS):
        out = [HEADER]
        for name in names[c::CHUNKS]:
            out.append('mbga_adj_' + name + ' = {' + NL)
            if islands.get(name):
                out.append(T + 'set_variable = { name = mbga_adj_islands value = %d }'
                           % islands[name] + NL)
            of = {}
            for a, b in sorted(by_state.get(name, ())):
                of.setdefault(a, []).append(b)
            for a in by_region.get(name, ()):
                of.setdefault(a, [])
            for a, neighbours in sorted(of.items()):
                here = '"variable_map(mbga_container_of|p:x%06X)"' % a
                out.append(T + 'if = {' + NL)
                out.append(T * 2 + 'limit = { exists = %s }' % here + NL)
                out.append(T * 2 + here + ' = {' + NL)
                if a in blocked:
                    out.append(T * 3 + 'set_variable = mbga_impassable' + NL)
                for b in neighbours:
                    out.append(T * 3 + 'add_to_variable_list = '
                               '{ name = mbga_adj target = p:x%06X }' % b + NL)
                out.append(T * 2 + '}' + NL)
                out.append(T + '}' + NL)
            out.append('}' + NL + NL)
        files['common/scripted_effects/mbga_baked_adjacency_%d.txt' % c] = ''.join(out)

    out = [HEADER,
           '# The mod calls this and takes whatever it gets. A map this table was not made' + NL,
           '# for matches no state here, nothing is filled, and the mod asks the engine' + NL,
           '# instead. A mod that redraws the map replaces these files with its own.' + NL + NL,
           'REPLACE_OR_CREATE:mbga_fill_adjacency_from_table = {' + NL]
    for i, name in enumerate(names):
        out.append(T + '%s = {' % ('if' if i == 0 else 'else_if') + NL)
        # The region stands on the left because ?= covers that side alone. A map without it
        # would otherwise raise an error here for every name it does not have.
        out.append(T * 2 + 'limit = { s:%s ?= var:mbga_active_state_region }' % name + NL)
        out.append(T * 2 + 'mbga_adj_%s = yes' % name + NL)
        out.append(T * 2 + 'set_variable = mbga_adj_from_table' + NL)
        out.append(T + '}' + NL)
    out.append('}' + NL)
    files['common/scripted_effects/zz_mbga_adjacency_dispatch.txt'] = ''.join(out)
    return files


def build(source, report=print):
    """Everything the adjacency table needs, as {relative path: text}."""
    by_state, blocked, islands = collect(source)
    by_region = {}
    for name, r in source.state_regions().items():
        here = [int(p[1:], 16) for p in r['provinces'] if int(p[1:], 16) in blocked]
        if here:
            by_region[name] = sorted(here)
    total = sum(len(v) for v in by_state.values())
    report('%d entries across %d state regions' % (total, len(by_state)))
    report('%d provinces cannot be marched through, in %d state regions'
           % (sum(len(v) for v in by_region.values()), len(by_region)))
    report('%d provinces have no land neighbour, in %d state regions'
           % (sum(islands.values()), len(islands)))
    return bake(by_state, blocked, by_region, islands)


def main():
    game = find_game()
    if not game:
        print('Victoria 3 not found. Set VIC3_GAME.')
        return 2
    mod = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    files = build(MapSource(game))
    for rel, text in sorted(files.items()):
        with open(os.path.join(mod, *rel.split('/')), 'w',
                  encoding='utf-8-sig', newline=NL) as f:
            f.write(text)
    mb = sum(len(t.encode('utf-8')) for t in files.values()) / (1024 * 1024)
    print('wrote %d files, %.1f MB' % (len(files), mb))
    return 0


if __name__ == '__main__':
    sys.exit(main())
