#!/usr/bin/env python3
"""Which province of each state region is its city, port, farm, mine or wood hub.

Nothing in the engine reads a hub back, so this is the one thing the mod cannot work out
while running. The names come from map_data/state_regions, where each region declares them.

Run tools/make_compat.py rather than this file: it does the whole set at once, for the base
game's map or for a mod's.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3_map import MapSource, find_game  # noqa: E402

HUB_ORDER = ('city', 'port', 'farm', 'mine', 'wood')
NL = '\n'
T = '\t'
HEADER = ('# Generated by tools/make_compat.py - do not edit by hand.' + NL
          + '# Source: map_data/state_regions/*.txt' + NL + NL)


def bake(regions):
    """-> ({relative path: file text}, hubs named). One flat table of variable maps.

    A variable map is keyed by the state region itself, so a state that was clicked looks its
    own hubs up rather than being compared against every region in the game.

    Every block is entered with ?=, the base game's own idiom for "if this still exists". A
    map that renames or drops a state region skips it without raising anything, and that
    state falls back to terrain names.
    """
    out = [HEADER,
           '# Filled once, into the caller. Key is the state region, value is the province' + NL,
           '# that is its hub. Country scope, and scope:mbga_hub_owner is that country.' + NL + NL,
           'mbga_fill_hub_maps = {' + NL,
           T + 'save_scope_as = mbga_hub_owner' + NL]
    named = 0
    for name in sorted(regions):
        hubs = regions[name]['hubs']
        if not hubs:
            continue
        out.append(T + 's:' + name + ' ?= {' + NL)
        out.append(T * 2 + 'save_scope_as = mbga_hub_state' + NL)
        out.append(T * 2 + 'scope:mbga_hub_owner = {' + NL)
        for kind in HUB_ORDER:
            if hubs.get(kind):
                named += 1
                out.append(T * 3 + 'add_to_variable_map = { name = mbga_hubmap_' + kind
                           + ' key = scope:mbga_hub_state value = p:' + hubs[kind] + ' }' + NL)
        out.append(T * 2 + '}' + NL)
        out.append(T + '}' + NL)
    out.append('}' + NL)
    return {'common/scripted_effects/mbga_baked_hubs.txt': ''.join(out)}, named


def build(source, report=print):
    """The hub table, as {relative path: text}."""
    regions = source.state_regions()
    files, named = bake(regions)
    with_hubs = sum(1 for r in regions.values() if r['hubs'])
    report('%d hubs named, in %d of %d state regions' % (named, with_hubs, len(regions)))
    return files


def main():
    game = find_game()
    if not game:
        print('Victoria 3 not found. Set VIC3_GAME.')
        return 2
    mod = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for rel, text in build(MapSource(game)).items():
        with open(os.path.join(mod, *rel.split('/')), 'w',
                  encoding='utf-8-sig', newline=NL) as f:
            f.write(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
