#!/usr/bin/env python3
"""The provinces of every state region, written out so the mod needs no geographic region.

MBGA lists the provinces of a state by walking a geographic region, because
every_province_in_<short_key> is the only thing in the game that produces a province scope.
A map whose states sit in no geographic region cannot be walked at all, and no list of names
fixes that.

This is the way round it. Province ids are literals, so nothing has to exist for them to
resolve: every province is filed under its state region outright, and the index is whole
before any walking starts.

Run tools/make_compat.py rather than this file: it does the whole set at once, for the base
game's map or for a mod's.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vic3_map import MapSource, find_game  # noqa: E402

NL = '\n'
T = '\t'
CHUNKS = 4
HEADER = ('# Generated by tools/make_compat.py - do not edit by hand.' + NL
          + '# Source: map_data/state_regions/*.txt' + NL + NL)


def bake(regions, water):
    """-> {relative path: file text}. One effect per chunk of state regions, and the hook.

    Each region is entered with ?=, the base game's own idiom for "if this still exists", so a
    table meeting a map that renames or drops a region skips it rather than raising anything.

    Water is left out. A sea province has no owner and can never be demanded, and the mod's own
    walk cannot file one either, since it files a province under its state and the sea has none.
    """
    names = sorted(n for n in regions
                   if any(int(p[1:], 16) not in water for p in regions[n]['provinces']))
    files = {}
    for c in range(CHUNKS):
        out = [HEADER]
        for name in names[c::CHUNKS]:
            ours = [p for p in regions[name]['provinces'] if int(p[1:], 16) not in water]
            out.append('mbga_index_' + name + ' = {' + NL)
            out.append(T + 's:' + name + ' ?= {' + NL)
            for pid in ours:
                out.append(T * 2 + 'add_to_variable_list = '
                           '{ name = mbga_region_provinces target = p:%s }' % pid + NL)
            out.append(T * 2 + 'change_global_variable = { name = mbga_index_count add = %d }'
                       % len(ours) + NL)
            out.append(T + '}' + NL)
            out.append('}' + NL + NL)
        files['common/scripted_effects/mbga_baked_index_%d.txt' % c] = ''.join(out)

    out = [HEADER,
           '# Fills the province index outright, so no geographic region is walked and no map' + NL,
           '# has to declare one.' + NL,
           '#' + NL,
           '# A map this table was not made for matches no region here and nothing is filled,' + NL,
           '# so the mod walks as it would without it. A mod that redraws the map replaces this' + NL,
           '# file with its own.' + NL + NL,
           'REPLACE_OR_CREATE:mbga_fill_index_from_table = {' + NL]
    for name in names:
        out.append(T + 'mbga_index_' + name + ' = yes' + NL)
    out.append('}' + NL)
    files['common/scripted_effects/zz_mbga_index_dispatch.txt'] = ''.join(out)
    return files


def build(source, report=print):
    """The province index, as {relative path: text}."""
    regions = source.state_regions()
    water = source.water()
    count = sum(1 for r in regions.values() for p in r['provinces']
                if int(p[1:], 16) not in water)
    report('%d land provinces across %d state regions' % (count, len(regions)))
    return bake(regions, water)


def main():
    game = find_game()
    if not game:
        print('Victoria 3 not found. Set VIC3_GAME.')
        return 2
    mod = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for rel, text in build(MapSource(game)).items():
        with open(os.path.join(mod, *rel.split('/')), 'w',
                  encoding='utf-8-sig', newline=NL) as f:
            f.write(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
