#!/usr/bin/env python3
"""Generate the hub table: which province of each state region is its city, port, farm,
mine or wood hub.

Nothing in the engine reads a hub back, so this is the one thing the mod cannot work out
while running. Re-run after a game update, or against a modded map.

Run: python tools/bake_hubs.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify_map_data import find_game, parse_state_regions  # noqa: E402

HUB_ORDER = ('city', 'port', 'farm', 'mine', 'wood')

MOD = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = ('# Generated by tools/bake_hubs.py - do not edit by hand.\n'
          '# Source: map_data/state_regions/*.txt\n\n')
NL = '\n'


def write(rel, text):
    path = os.path.join(MOD, *rel.split('/'))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8-sig', newline='\n') as f:
        f.write(text)
    return path


def short_key(name):
    """STATE_WALLONIA -> mbga_wallonia. The mbga_ prefix keeps these out of the way of
    vanilla and other mods, which share one namespace of geographic region short keys."""
    return 'mbga_' + name[len('STATE_'):].lower() if name.startswith('STATE_')         else 'mbga_' + name.lower()




def bake_hub_map(regions):
    """One flat table: state region -> hub province, as variable maps on the caller.

    There used to be two files: an effect per state region setting five variables, and a
    dispatcher of 781 if/else_if branches picking which of those effects to call. The
    dispatcher is gone: a variable map is keyed by the state region itself, so the state
    that was clicked looks its own hubs up instead of being compared against 781 names.

    Every block is entered with ?=, which is the base game's own idiom for "if this still
    exists". A map that renames or drops a state region simply skips it, so no error is
    raised and that state quietly falls back to terrain names.
    """
    out = [HEADER,
           '# Filled once, into the caller. Key is the state region, value is the province' + NL +
           '# that is its hub. Country scope, and scope:mbga_hub_owner is that country.' + NL + NL,
           'mbga_fill_hub_maps = {' + NL,
           '	save_scope_as = mbga_hub_owner' + NL]
    for name in sorted(regions):
        hubs = regions[name]['hubs']
        if not hubs:
            continue
        out.append('	s:' + name + ' ?= {' + NL)
        out.append('		save_scope_as = mbga_hub_state' + NL)
        out.append('		scope:mbga_hub_owner = {' + NL)
        for kind in HUB_ORDER:
            pid = hubs.get(kind)
            if pid:
                out.append('			add_to_variable_map = { name = mbga_hubmap_' + kind
                           + ' key = scope:mbga_hub_state value = p:' + pid + ' }' + NL)
        out.append('		}' + NL)
        out.append('	}' + NL)
    out.append('}' + NL)
    return ''.join(out)


def main():
    game = find_game()
    if not game:
        print('Victoria 3 not found. Set VIC3_GAME.')
        return 2
    regions = {n: r for n, r in parse_state_regions(game).items() if r['provinces']}

    written = [
        write('common/scripted_effects/mbga_baked_hubs.txt', bake_hub_map(regions)),
    ]

    for p in written:
        print(f'{os.path.relpath(p, MOD):<58}{os.path.getsize(p) // 1024:>6} KB')
    total = sum(len(r['provinces']) for r in regions.values())
    named = sum(len(r['hubs']) for r in regions.values())
    print(f'\nstate regions: {len(regions)}   provinces: {total}   named hubs: {named}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
