#!/usr/bin/env python3
"""Cross-check our parse of the province data against the game's own generated files.

map_data/province_terrains.txt is generated by the game from provinces.png, so it is
an independent ground truth for the set of province ids. If our parse of
map_data/state_regions/*.txt disagrees with it, the bake is wrong and everything
built on top of it would be wrong too.
"""
import os
import re
import sys
from collections import Counter, defaultdict

HEX = re.compile(r'"?(x[0-9A-Fa-f]{6})"?')
HUBS = ('city', 'port', 'farm', 'mine', 'wood')


def find_game():
    for base in (os.environ.get('VIC3_GAME'),
                 r'C:\Steam\steamapps\common\Victoria 3\game'):
        if base and os.path.isdir(os.path.join(base, 'map_data')):
            return base
    for drive in 'CDEFGH':
        p = f'{drive}:\\Steam\\steamapps\\common\\Victoria 3\\game'
        if os.path.isdir(os.path.join(p, 'map_data')):
            return p
    return None


def read(path):
    return open(path, encoding='utf-8-sig', errors='replace').read().replace('\r', '')


def parse_region_text(text, filename=''):
    """One state_regions file -> {state_region: {'provinces', 'hubs', 'file'}}"""
    out = {}
    # strip comments outside quotes
    clean = []
    for line in text.split('\n'):
        q, buf = False, ''
        for ch in line:
            if ch == '"':
                q = not q
            if ch == '#' and not q:
                break
            buf += ch
        clean.append(buf)
    text = '\n'.join(clean)

    depth, cur, body = 0, None, []
    for line in text.split('\n'):
        if depth == 0:
            m = re.match(r'^\s*([A-Z_][A-Z0-9_]*)\s*=\s*\{', line)
            if m:
                cur, body = m.group(1), []
        if cur:
            body.append(line)
        depth += line.count('{') - line.count('}')
        if cur and depth == 0:
            blob = '\n'.join(body)
            pm = re.search(r'provinces\s*=\s*\{([^}]*)\}', blob, re.S)
            provs = HEX.findall(pm.group(1)) if pm else []
            hubs = {}
            for h in HUBS:
                hm = re.search(r'^\s*' + h + r'\s*=\s*"?(x[0-9A-Fa-f]{6})"?', blob, re.M)
                if hm:
                    hubs[h] = hm.group(1)
            # keep the original casing: p: lookups are matched against the
            # ids exactly as the game writes them
            out[cur] = {'provinces': provs, 'hubs': hubs, 'file': filename}
            cur = None
    return out


def parse_state_regions(game):
    """-> {state_region: {'provinces': [...], 'hubs': {type: id}, 'file': name}}"""
    out = {}
    base = os.path.join(game, 'map_data', 'state_regions')
    for fn in sorted(os.listdir(base)):
        if fn.endswith('.txt'):
            out.update(parse_region_text(read(os.path.join(base, fn)), fn))
    return out


def parse_terrain_text(text):
    """-> {province_id: terrain}"""
    out = {}
    for line in text.split('\n'):
        m = re.match(r'^\s*(x[0-9A-Fa-f]{6})\s*=\s*"?([a-z_]+)"?', line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def parse_terrains(game):
    """-> {province_id: terrain}, from the game's own generated file."""
    return parse_terrain_text(read(os.path.join(game, 'map_data', 'province_terrains.txt')))


def main():
    game = find_game()
    if not game:
        print('Victoria 3 not found. Set VIC3_GAME.')
        return 2
    print(f'game: {game}\n')

    regions = parse_state_regions(game)
    terrains = parse_terrains(game)

    ours = [p for r in regions.values() for p in r['provinces']]
    up = {p.upper(): p for p in terrains}
    ours_set = set(ours)
    print(f'state regions parsed      : {len(regions)}')
    print(f'provinces in state regions: {len(ours)} ({len(ours_set)} unique)')
    print(f'provinces in terrains file: {len(terrains)}')
    print()

    fail = False

    dupes = [p for p, n in Counter(ours).items() if n > 1]
    if dupes:
        fail = True
        owner = defaultdict(list)
        for name, r in regions.items():
            for p in r['provinces']:
                if p in set(dupes):
                    owner[p].append(name)
        print(f'!! {len(dupes)} province(s) listed in more than one state region:')
        for p in dupes[:5]:
            print(f'     {p} -> {owner[p]}')
    else:
        print('ok  no province belongs to two state regions')

    missing = {p for p in ours_set if p.upper() not in up}
    if missing:
        fail = True
        print(f'!! {len(missing)} province(s) in state regions but absent from the '
              f'generated terrain file, e.g. {sorted(missing)[:5]}')
    else:
        print('ok  every province we parsed exists in the game-generated terrain file')

    have = {p.upper() for p in ours_set}
    extra = {p for p in terrains if p.upper() not in have}
    water = {p for p in extra if terrains[p] in ('ocean', 'lakes', 'lake', 'sea')}
    land_extra = extra - water
    print(f'ok  {len(water)} water province(s) correctly absent from state regions')
    if land_extra:
        print(f'note {len(land_extra)} land province(s) belong to no state region, '
              f'terrains: {sorted({terrains[p] for p in land_extra})}')

    bad_hub, case_hub = [], []
    for n, r in regions.items():
        exact = set(r['provinces'])
        upper = {p.upper() for p in exact}
        for h, pid in r['hubs'].items():
            if pid in exact:
                continue
            (case_hub if pid.upper() in upper else bad_hub).append((n, h, pid))
    if bad_hub:
        fail = True
        print(f'!! {len(bad_hub)} hub(s) point outside their own state region, '
              f'e.g. {bad_hub[:3]}')
    else:
        print('ok  every hub province belongs to its own state region')
    if case_hub:
        print(f'note {len(case_hub)} hub field(s) in the game data are cased '
              f'differently from the province list, e.g. {case_hub[:2]} - vanilla '
              f'loads these fine, so p: lookups ignore case')

    empty = [n for n, r in regions.items() if not r['provinces']]
    if empty:
        print(f'note {len(empty)} state region(s) with no provinces: {empty[:5]}')

    sizes = sorted(len(r['provinces']) for r in regions.values() if r['provinces'])
    print(f'\nprovinces per state region: min {sizes[0]}, median '
          f'{sizes[len(sizes) // 2]}, max {sizes[-1]}')
    hubbed = sum(1 for r in regions.values() if r['hubs'])
    print(f'state regions with at least one named hub: {hubbed}/{len(regions)}')

    print('\n' + ('MISMATCH - do not bake from this parse' if fail
                  else 'parse agrees with the game data'))
    return 1 if fail else 0


if __name__ == '__main__':
    sys.exit(main())
